app:
  name: spring-poc
  version: 1.0
  feature-flags: alpha,beta,gamma

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:
  cache:
    type: caffeine
    cache-names: products
    caffeine:
      spec: maximumSize=100,expireAfterWrite=10m

logging:
  level:
    root: WARN
    org.springframework: WARN
    com.github.vikthorvergara: INFO
